/* src/config.h.  Generated by configure.  */
/* src/config.h.in.  Generated from configure.in by autoheader.  */

/* Name of package */
#define PACKAGE "tunneler"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "tvkalvas@jyu.fi"

/* Define to the full name of this package. */
#define PACKAGE_NAME "tunneler"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "tunneler 1.1.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "tunneler"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.1.1"

/* Version number of package */
#define VERSION "1.1.1"
